package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.DataElement;
/** 
 * Class Generated by BTT Tool Created since: 2018/02/07 03:52:40
 */
public class AccountStatementOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc --> <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  this.addElement((DataElement)this.getElementAt("MockData.cardList").clone());
	  this.addElement((DataElement)this.getElementAt("MockData.total_balance").clone());
	  this.addElement((DataElement)this.getElementAt("MockData.card_amount").clone());
  }
}
