package com.ibm.btt.application.op;
import java.util.Enumeration;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
import com.ibm.btt.base.types.impl.Currency;
/** 
 * Class Generated by BTT Tool Created since: 2018/02/06 14:39:22
 */
public class CheckBalanceOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc --> <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  String id = (String)this.getValueAt("card_id");
	  Currency balance = null;
	  
	  Enumeration<KeyedCollection> cards = ((IndexedCollection)this.getElementAt("cardList")).getElements().elements();
	  while(cards.hasMoreElements())
	  {
		  KeyedCollection card = cards.nextElement();
		  if (id.equals(card.getValueAt("card_id")))
		  {
			  balance = (Currency)card.getValueAt("balance");
			  break;
		  }
	  }
	  
	  if (balance != null)
	  {
		  this.setValueAt("balance", balance);
	  }
//	  this.fireExitEvent("ok");
  }
}
