package com.ibm.btt.application.op;
import java.util.Vector;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.IndexedCollection;
import com.ibm.btt.base.KeyedCollection;
/** 
 * Class Generated by BTT Tool
 * Created since: 2017/12/04 14:52:38
 */
public class PayeeOp extends BTTServerOperation {

  public void execute() throws Exception {
	  KeyedCollection form = (KeyedCollection)getContext().getElementAt("payeeForm");
	  IndexedCollection payeeList = (IndexedCollection) getContext().getElementAt("payeeList");
	  KeyedCollection payeeKC = (KeyedCollection) form.tryGetElementAt("payee").clone();
	  String command = (String) form.getValueAt("command");
	  if(null != payeeKC){
		  switch (command) {
		  case "add":
			  payeeList.addElement(payeeKC);
			  break;
		  case "edit":{
				  Vector<KeyedCollection> cL = payeeList.getElements();
				  boolean flag = true;
				  for (KeyedCollection keyedCollection : cL) {
					  if(keyedCollection.tryGetValueAt("name").equals(payeeKC.tryGetValueAt("name"))){
						  keyedCollection.setValueAt("phone", payeeKC.tryGetValueAt("phone"));
						  keyedCollection.setValueAt("card_id", payeeKC.tryGetValueAt("card_id"));
						  flag = false;
						  break;
					  }
				  }
				  if(flag){				  
					  getContext().setValueAt("message", "Can't find the record of payee by name.");
				  }
			  }
			  break;
		  case "delete":{
				  Vector<KeyedCollection> cL = payeeList.getElements();
				  KeyedCollection find = null;
				  for (KeyedCollection keyedCollection : cL) {
					  if(keyedCollection.tryGetValueAt("name").equals(payeeKC.tryGetValueAt("name"))){
						  find = keyedCollection;
						  break;
					  }
				  }
				  if(null != find){
					  cL.remove(find);
				  }else{
					  getContext().setValueAt("message", "Can't find the record of payee by name.");
				  }
			  }
			  break;
		  default:
			  getContext().setValueAt("message", "Unkonwn Command");
			  break;
		  }
	  }else{
		  getContext().setValueAt("message", "Can't get payee information");
	  }
	  fireExitEvent("result");
  }
}
