package com.ibm.btt.application.op;
import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.DataElement;
/** 
 * Class Generated by BTT Tool Created since: 2018/02/06 14:22:38
 */
public class PayeeListOp extends BTTServerOperation {
  /** 
 * <!-- begin-user-doc --> <!-- end-user-doc -->
 */
  public void execute() throws Exception {
	  this.addElement((DataElement)this.getElementAt("MockData.payeeList").clone());
	  this.fireExitEvent("OK");
  }
}
