/*_
 * UNICOM(R) Multichannel Bank Transformation Toolkit Source Materials 
 * Copyright(C) 2011 - 2017 UNICOM Systems, Inc. - All Rights Reserved 
 * Highly Confidential Material - All Rights Reserved 
 * THE INFORMATION CONTAINED HEREIN CONSTITUTES AN UNPUBLISHED 
 * WORK OF UNICOM SYSTEMS, INC. ALL RIGHTS RESERVED. 
 * NO MATERIAL FROM THIS WORK MAY BE REPRINTED, 
 * COPIED, OR EXTRACTED WITHOUT WRITTEN PERMISSION OF 
 * UNICOM SYSTEMS, INC. 818-838-0606 
 */

package com.ibm.btt.application.op;

import com.ibm.btt.base.BTTServerOperation;
import com.ibm.btt.base.Context;
import com.ibm.btt.base.ContextFactory;

/**
 * Class Generated by BTT Tool Created since: 2010/12/13 17:36:42
 */
public class StartUpOp extends BTTServerOperation {

	public static final java.lang.String COPYRIGHT = 
              "UNICOM(R) Multichannel Bank Transformation Toolkit Source Materials "
			+ "Copyright(C) 2011 - 2017 UNICOM Systems, Inc. - All Rights Reserved "
			+ "Highly Confidential Material - All Rights Reserved "
			+ "THE INFORMATION CONTAINED HEREIN CONSTITUTES AN UNPUBLISHED "
			+ "WORK OF UNICOM SYSTEMS, INC. ALL RIGHTS RESERVED. "
			+ "NO MATERIAL FROM THIS WORK MAY BE REPRINTED, "
			+ "COPIED, OR EXTRACTED WITHOUT WRITTEN PERMISSION OF "
			+ "UNICOM SYSTEMS, INC. 818-838-0606 ";

	/**
	 * <!-- begin-user-doc --> <!-- end-user-doc -->
	 */
	public void execute() throws Exception {
		System.out.println("StartUpOp");
		Context root = ContextFactory.getRoot();
		
		if (root == null) {
			System.out.println("Creating root ctx");
			root = ContextFactory.createContext("branchServer");
		}
		
		Context sessionCtx = ContextFactory.createContext("sessionCtx");
		sessionCtx.chainTo(root);

		this.getContext().chainTo(sessionCtx);

	}
}

